V8PATH = ../../../src/3rdparty/v8
V8LIBPATH = $(V8PATH)
V8INCPATH = $(V8PATH)/include
SOURCES = v8main.cpp v8test.cpp

release-m32:
	g++ -o v8test_release_m32 -m32 -O2 -I$(V8INCPATH) $(SOURCES) -lpthread -L$(V8LIBPATH) -lv8

debug-m32:
	g++ -o v8test_debug_m32 -m32 -g -I$(V8INCPATH) $(SOURCES) -lpthread -L$(V8LIBPATH) -lv8_g

release:
	g++ -o v8test_release -O2 -I$(V8INCPATH) $(SOURCES) -lpthread -L$(V8LIBPATH) -lv8

debug:
	g++ -o v8test_debug -g -I$(V8INCPATH) $(SOURCES) -lpthread -L$(V8LIBPATH) -lv8_g

mips-release:
	g++ -o v8test_mips_release -g -I$(V8INCPATH) $(SOURCES) -lpthread -L$(V8LIBPATH)/out/mips.release/lib.target/ -Wl,-rpath,$(V8LIBPATH)/out/mips.release/lib.target -lv8

mips-debug:
	g++ -o v8test_mips_debug -g -I$(V8INCPATH) $(SOURCES) -lpthread -L$(V8LIBPATH)/out/mips.debug/lib.target/ -Wl,-rpath,$(V8LIBPATH)/out/mips.debug/lib.target -lv8

arm-release:
	g++ -o v8test_arm_release -g -I$(V8INCPATH) $(SOURCES) -lpthread -L$(V8LIBPATH)/out/arm.release/lib.target/ -Wl,-rpath,$(V8LIBPATH)/out/arm.release/lib.target -lv8

arm-debug:
	g++ -o v8test_arm_debug -g -I$(V8INCPATH) $(SOURCES) -lpthread -L$(V8LIBPATH)/out/arm.debug/lib.target/ -Wl,-rpath,$(V8LIBPATH)/out/arm.debug/lib.target -lv8
